"""criar tabelas favoritos, alertas e alertas_disparos

Revision ID: 326d8bde7b4c
Revises: cddad364cc3a
Create Date: 2026-07-05 21:27:24.881756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '326d8bde7b4c'
down_revision: Union[str, None] = 'cddad364cc3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('parametros_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_ticker'), 'alertas', ['ticker'], unique=False)
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', name='uq_favorito_ticker')
    )
    op.create_index(op.f('ix_favoritos_ticker'), 'favoritos', ['ticker'], unique=False)
    op.create_table('alertas_disparos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alerta_id', sa.Integer(), nullable=False),
    sa.Column('disparado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valor_no_momento', sa.String(length=100), nullable=False),
    sa.Column('lido', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_disparos_alerta_id'), 'alertas_disparos', ['alerta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertas_disparos_alerta_id'), table_name='alertas_disparos')
    op.drop_table('alertas_disparos')
    op.drop_index(op.f('ix_favoritos_ticker'), table_name='favoritos')
    op.drop_table('favoritos')
    op.drop_index(op.f('ix_alertas_ticker'), table_name='alertas')
    op.drop_table('alertas')
    # ### end Alembic commands ###
