"""adicionar usuario_id em favoritos e alertas

Revision ID: c6360eba0338
Revises: 8a1f4c9e2b7d
Create Date: 2026-07-08 23:08:03.815259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6360eba0338'
down_revision: Union[str, None] = '8a1f4c9e2b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertas', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_alertas_usuario_id'), 'alertas', ['usuario_id'], unique=False)
    op.create_foreign_key(None, 'alertas', 'usuarios', ['usuario_id'], ['id'])
    op.add_column('favoritos', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.drop_constraint('uq_favorito_ticker', 'favoritos', type_='unique')
    op.create_index(op.f('ix_favoritos_usuario_id'), 'favoritos', ['usuario_id'], unique=False)
    op.create_unique_constraint('uq_favorito_usuario_ticker', 'favoritos', ['usuario_id', 'ticker'])
    op.create_foreign_key(None, 'favoritos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favoritos', type_='foreignkey')
    op.drop_constraint('uq_favorito_usuario_ticker', 'favoritos', type_='unique')
    op.drop_index(op.f('ix_favoritos_usuario_id'), table_name='favoritos')
    op.create_unique_constraint('uq_favorito_ticker', 'favoritos', ['ticker'])
    op.drop_column('favoritos', 'usuario_id')
    op.drop_constraint(None, 'alertas', type_='foreignkey')
    op.drop_index(op.f('ix_alertas_usuario_id'), table_name='alertas')
    op.drop_column('alertas', 'usuario_id')
    # ### end Alembic commands ###
