"""criar tabelas ativos e cotacoes_historicas

Revision ID: cddad364cc3a
Revises: 
Create Date: 2026-07-05 14:15:02.511275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cddad364cc3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('setor', sa.String(length=100), nullable=True),
    sa.Column('moeda', sa.String(length=10), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ativos_ticker'), 'ativos', ['ticker'], unique=True)
    op.create_table('cotacoes_historicas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('abertura', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('maxima', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('minima', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fechamento', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo_id', 'data', name='uq_ativo_data')
    )
    op.create_index(op.f('ix_cotacoes_historicas_ativo_id'), 'cotacoes_historicas', ['ativo_id'], unique=False)
    op.create_index(op.f('ix_cotacoes_historicas_data'), 'cotacoes_historicas', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotacoes_historicas_data'), table_name='cotacoes_historicas')
    op.drop_index(op.f('ix_cotacoes_historicas_ativo_id'), table_name='cotacoes_historicas')
    op.drop_table('cotacoes_historicas')
    op.drop_index(op.f('ix_ativos_ticker'), table_name='ativos')
    op.drop_table('ativos')
    # ### end Alembic commands ###
